# Generated by Django 4.0.2 on 2023-09-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('doacaoId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('item', models.CharField(max_length=100)),
                ('doador', models.CharField(max_length=100)),
                ('donatario', models.CharField(max_length=100)),
                ('dataDoacao', models.CharField(max_length=100)),
                ('recebido', models.CharField(max_length=100)),
                ('pedidos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('motivo', models.CharField(max_length=100)),
                ('quantidade', models.CharField(max_length=100)),
                ('fotos', models.CharField(max_length=100)),
                ('tempoDeUso', models.CharField(max_length=100)),
                ('condicao', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.CharField(default='https://i.imgur.com/3GwVr0S.png', max_length=100)),
                ('bio', models.TextField()),
                ('listaDeDoacao', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('nascimento', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=1)),
                ('nota', models.IntegerField()),
                ('countAvaliacao', models.IntegerField()),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('logradouro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
    ]
