# Generated by Django 4.0.2 on 2023-09-21 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('motivo', models.CharField(max_length=100)),
                ('quantidade', models.CharField(max_length=100)),
                ('fotos', models.CharField(max_length=100)),
                ('tempoDeUso', models.CharField(max_length=100)),
                ('condicao', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('telefone', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('nota', models.IntegerField()),
                ('countAvaliacao', models.IntegerField()),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('logradouro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='doacao', serialize=False, to='UserApp.item', unique=True)),
                ('dataDoacao', models.DateField()),
                ('recebido', models.CharField(max_length=100)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes_feitas', to='UserApp.user')),
                ('donatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes_recebidas', to='UserApp.user')),
            ],
        ),
    ]
