# Generated by Django 4.0.2 on 2023-09-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='countAvaliacao',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='listaDeDoacao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nota',
            field=models.IntegerField(null=True),
        ),
    ]
