# Generated by Django 4.1.13 on 2023-11-08 21:04

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='media')),
                ('bio', models.TextField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=100, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('idade', models.IntegerField(null=True)),
                ('sexo', models.CharField(blank=True, max_length=100, null=True)),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('countAvaliacao', models.IntegerField(blank=True, null=True)),
                ('rua', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('motivo', models.CharField(max_length=100)),
                ('quantidade', models.CharField(default='1', max_length=100)),
                ('fotos', models.CharField(max_length=100)),
                ('tempoDeUso', models.CharField(default='0', max_length=100)),
                ('condicao', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dono', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('dataDoacao', models.DateField(auto_now_add=True)),
                ('recebido', models.CharField(max_length=100)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doador', to=settings.AUTH_USER_MODEL)),
                ('donatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donatario', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='base.item')),
                ('pedidos', models.ManyToManyField(related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='listaDeDoacao',
            field=models.ManyToManyField(blank=True, null=True, to='base.doacao'),
        ),
    ]
