# Generated by Django 4.1.13 on 2023-11-07 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.FileField(blank=True, null=True, upload_to='media')),
                ('bio', models.TextField()),
                ('telefone', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('idade', models.IntegerField(null=True)),
                ('sexo', models.CharField(max_length=100)),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('countAvaliacao', models.IntegerField(blank=True, null=True)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('logradouro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('motivo', models.CharField(max_length=100)),
                ('quantidade', models.CharField(default='1', max_length=100)),
                ('fotos', models.CharField(max_length=100)),
                ('tempoDeUso', models.CharField(default='0', max_length=100)),
                ('condicao', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('doacaoId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('item', models.CharField(max_length=100)),
                ('dataDoacao', models.DateField(auto_now_add=True)),
                ('recebido', models.CharField(max_length=100)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doador', to=settings.AUTH_USER_MODEL)),
                ('donatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donatario', to=settings.AUTH_USER_MODEL)),
                ('pedidos', models.ManyToManyField(related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='listaDeDoacao',
            field=models.ManyToManyField(to='base.doacao'),
        ),
    ]
