# Generated by Django 4.1.13 on 2023-11-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('doacaoId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('item', models.CharField(max_length=100)),
                ('doador', models.CharField(max_length=100)),
                ('donatario', models.CharField(max_length=100)),
                ('dataDoacao', models.CharField(max_length=100)),
                ('recebido', models.CharField(max_length=100)),
                ('pedidos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('motivo', models.CharField(max_length=100)),
                ('quantidade', models.CharField(default='1', max_length=100)),
                ('fotos', models.CharField(max_length=100)),
                ('tempoDeUso', models.CharField(default='0', max_length=100)),
                ('condicao', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=100, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField()),
                ('listaDeDoacao', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('idade', models.IntegerField(null=True)),
                ('sexo', models.CharField(max_length=100)),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('countAvaliacao', models.IntegerField(blank=True, null=True)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('logradouro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
