# Generated by Django 4.1.13 on 2023-11-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_doacao_item_user_delete_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
