# Generated by Django 4.1.13 on 2023-11-07 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nome',
            new_name='username',
        ),
    ]
