# Generated by Django 4.0.2 on 2023-12-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='recebido',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
