# Generated by Django 4.0.2 on 2023-12-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_item_recebido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='recebido',
            field=models.BooleanField(default=False),
        ),
    ]
