# Generated by Django 5.0 on 2023-12-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_item_recebido'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='punicao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
