# Generated by Django 4.1.13 on 2023-11-07 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doacao',
            old_name='doacaoId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userId',
            new_name='id',
        ),
    ]
