# Generated by Django 4.0.2 on 2023-11-08 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_doacaoid_doacao_id_rename_itemid_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.item'),
        ),
        migrations.AlterField(
            model_name='user',
            name='listaDeDoacao',
            field=models.ManyToManyField(blank=True, null=True, to='base.Doacao'),
        ),
    ]
